function D = delsq(G)
%DELSQ  Construct five-point finite difference Laplacian.
%   delsq(G) is the sparse form of the two-dimensional,
%   5-point discrete negative Laplacian on the grid G.
%   The grid G can be generated by NUMGRID or NESTED.
%
%   See also NUMGRID, DEL2, DELSQDEMO.

%   C. Moler, 7-16-91.
%   Copyright 1984-2002 The MathWorks, Inc. 
%   $Revision: 1.1.6.2 $  $Date: 2010/09/02 13:36:57 $

%--
% Edits : Tim Rudge (TJR), trying make boundary conditions zero flux

[m,~] = size(G);

% Indices of interior points
p = find(G);

% Connect interior points to themselves with 4's.
i = G(p);
j = G(p);
s = 4*ones(size(p));

% for k = north, east, south, west
for k = [-1 m 1 -m]
   % Possible neighbors in k-th direction
   Q = G(p+k);
   % Neighbours in opposite direction (TJR)
   R = G(p-k)
   
   % Index of points with interior neighbors
   q = find(Q);
   % boundary points (TJR)
   nq = find(Q==0); 
   
   % TJR, note: this bit ignores neighbors outside the domain,
   % effectively then assuming they are =0
   % Connect interior points to neighbors with -1's.
   i = [i; G(p(q))];
   j = [j; Q(q)];
   s = [s; -ones(length(q),1)];
   
   % Here we need to account for the boundary condition
   % that grad(u).n=0 at the boundary (n=normal)
   %
   % This means (du/dx)n_x = (du/dy)n_y
   % How do we do this??
end
D = sparse(i,j,s);
