function D = delsq(G)
%DELSQ  Construct five-point finite difference Laplacian.
%   delsq(G) is the sparse form of the two-dimensional,
%   5-point discrete negative Laplacian on the grid G.
%   The grid G can be generated by NUMGRID or NESTED.
%
%   See also NUMGRID, DEL2, DELSQDEMO.

%   C. Moler, 7-16-91.
%   Copyright 1984-2002 The MathWorks, Inc. 
%   $Revision: 1.1.6.2 $  $Date: 2010/09/02 13:36:57 $

%--
% Edits : Tim Rudge (TJR), trying make boundary conditions zero flux

[m,~] = size(G);

% Indices of interior points
p = find(G);

% Connect interior points to themselves with 4's.
i = G(p);
j = G(p);
s = 4*ones(size(p));

% for k = north, east, south, west
for k = [-1 m 1 -m]
   % Possible neighbors in k-th direction
   Q = G(p+k);
   
   % Index of points with interior neighbors
   q = find(Q);
   
   % Neighbours in opposite direction (TJR)
   R = G(p(q)-k);
   nr = find(R==0); %TJR, points with no neighbour in opposite direction

   % TJR, note: this bit ignores neighbors outside the domain,
   % effectively then assuming they are =0
   % Connect interior points to neighbors with -1's.
   i = [i; G(p(q))];
   j = [j; Q(q)];
   
   % TJR, here for points at the boundary that have no neighbour
   % in direction -k should get a 2 instead of 1
   %s = [s; -ones(length(q),1)];
   w = ones(length(q),1);
   w(nr) = 1;
   s = [s; -w];
   

end
D = sparse(i,j,s);
